redis:
    image: redis
    container_name: redis
    restart: always
hubot:
    image: fullbright/hubot
    container_name: garcia-hubot
    ports:
        - "9081:8080"
    restart: always
    links:
        - redis:redis
    env_file:
        - $PWD/.env
    volumes:
        - $PWD/build:/opt 
